name: cpp-linter

on: 
  pull_request:
  push:
    branches: main
    
env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'
    
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      working-directory: ./firmware
      run: cmake -B build -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build
      working-directory: ./firmware
      run: cmake --build build
      
    - name: clang-tidy
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
        lines-changed-only: true
        repo-root: ./firmware
        version: 12
        ignore: lib|build
        database: build/compile_commands.json
     
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: build-artifacts
        path: ./firmware/build/**
        if-no-files-found: error
        retention-days: 90
        

