name: Merge Criteria

on:
  pull_request:
  push:
    branches: main

env:
  # CMake build type (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '13'
        check-path: 'firmware'
        exclude-regex: '(firmware/lib)'

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      working-directory: ./firmware
      run: cmake -B build -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Build
      working-directory: ./firmware
      run: cmake --build build

    - name: Upload Compile Commands
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: compile-commands
        path: ./firmware/build/compile_commands.json
        if-no-files-found: error
        retention-days: 1

  clang-tidy:
    name: Clang-Tidy Check
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Download Compile Commands
      uses: actions/download-artifact@v3
      with:
        name: compile-commands
        path: ./firmware/build/

    - name: clang-tidy review
      uses: ZedThree/clang-tidy-review@v0.10.1
      id: review
      with:
        clang_tidy_version: 14
        build_dir: firmware/build
        config_file: firmware/.clang-tidy
        exclude: firmware/lib
        max_comments: 50

    - if: steps.review.outputs.total_comments > 0
      run: exit 1
